### PR TITLE
Setting up Pipenv and Django

### LINKED ISSUE #4: Setting up Pipenv and Django
- Updating the Pipenv that the project will work on Python version 3
- Installing Django
- Bootstrapping a Django website
- Providing HTTP access into our VM

### PR DESCRIPTION
**Pull request by AlonShakaroff**
- Updated the Pipenv that the project will work on Python version 3
    - Installed Django
    - Bootstraped a Django website
    - Provided HTTP access into our VM

fix #4

### CODE REVIEW

**Comment by OmerCS8** [comment]
Looks good to me!

**Review by MatanP12 — APPROVED** [review]
Looks good!

**Comment by natifridman** [comment]
@AlonShakaroff Where are you installing pipenv and Django?

**Comment by AlonShakaroff** [comment]
> @AlonShakaroff Where are you installing pipenv?

My bad, pipenv installment is not a part of the PR,
I edited it out of the PR.

**Comment by AlonShakaroff** [comment]
> You should also edit it in the issue

I did

**Comment by yulisuliman** [comment]
Looks great

**Comment by abiton1** [comment]
Can you please also update the issue's title?
it is now `Installing Pipenv and setting up Django`

**Review by natifridman — APPROVED** [review]

**Pull request merged**
