### PR TITLE
Adding a Direct Message app

### LINKED ISSUE #31: Adding message app
Adding the message app including:
models, tests, views, init, admin and apps python files

### PR DESCRIPTION
**Pull request by TomerNewmanPrograms**
Adding the direct_message app, currently its an empty shell.
The name was changed from "directMessage" due to naming conventions.
Closed the previous PR in order to not be dependent on #36 

Fix #31

### CODE REVIEW

**Review by MatanP12 — APPROVED** [review]
LGTM

**Review by OmerCS8 — APPROVED** [review]
LGTM

**Review by AlonShakaroff — DISMISSED** [review]
LGTM

**Comment by natifridman** [comment]
Please link the PR to an issue with the relevant word

**Comment by TomerNewmanPrograms** [comment]
> Please link the PR to an issue with the relevant word

Done, the issue was edited now.

**Review by OmerCS8 — APPROVED** [review]
LGTM

**Review by MatanP12 — APPROVED** [review]
LGTM

In the 1st comment write `fixing` instead of `Fixing` and the issue will be closed when the PR is merged.

**Comment by TomerNewmanPrograms** [comment]
> LGTM
> 
> In the 1st comment write `fix` instead of `Fixing` and the issue will be closed when the PR is merged.

Done

**Comment by TomerNewmanPrograms** [comment]
> LGTM
> 
> In the 1st comment write `fix` instead of `Fixing` and the issue will be closed when the PR is merged.

Done

**Review by yulisuliman — APPROVED** [review]

**Comment by natifridman** [comment]
Please resolve the conflicts

**Review by MatanP12 — DISMISSED** [review]
LGTM

**Review by yulisuliman — DISMISSED** [review]

**Comment by TomerNewmanPrograms** [comment]
> Please resolve the conflicts

Done.
As you can see by the commit history, I've encountered some difficulties with the conflict change :)
Now its working well

**Review by MatanP12 — APPROVED** [review]
LGTM

**Review by natifridman — APPROVED** [review]

**Pull request closed without merging**
