### PR TITLE
Updating documantation files

### LINKED ISSUE #59: Updating the DFD and ERD
Adding all the models to the DFD and ERD charts

### PR DESCRIPTION
**Pull request by TomerNewmanPrograms**
- Updating ERD
- Updating DFD
Contains all the models.

fix #59

### CODE REVIEW

**Review by MatanP12 — APPROVED** [review]
LGTM

**Review by OmerCS8 — APPROVED** [review]
LGTM

**Comment by natifridman** [comment]
Is this something that will be able to be ready for the next demo? It looks like you added a lot of models

**Comment by OmerCS8** [comment]
> Is this something that will be able to be ready for the next demo? It looks like you added a lot of models

This is the final goal that we hope to achieve.
We do have prioritized models, and do understand that it is possible that we won't be able to accomplish all the features mentioned in the ERD and DFD.
In that case, we will modify the diagrams accordingly.

**Review by natifridman — APPROVED** [review]

**Comment by OmerCS8** [comment]
> So should we merge it or not?

I think yes

**Pull request merged**
