### PR TITLE
Change app name and adding images

### LINKED ISSUE #16: Change app name and adding images
- Change app name from homepage to resumeApp
- Adding more images of the logo suitable for white background

### PR DESCRIPTION
**Pull request by OmerCS8**
- Change app name from homepage to resumeApp
- Adding some images of the logo
fix #16

### CODE REVIEW

**Review by AlonShakaroff — APPROVED** [review]
Looks good, nice colors!

**Review by TomerNewmanPrograms — APPROVED** [review]
LGTM

**Review by yulisuliman — APPROVED** [review]
Looks great!

**Review by MatanP12 — APPROVED** [review]
LGTM nice pictures!

**Review by natifridman — APPROVED** [review]

**Pull request merged**
