### PR TITLE
Adding vagrantfile and gitignore

### LINKED ISSUE #1: Creating a Linux development environment with Vagrant and VirtualBox
bringing up a VM with Vagrant and Setting up file sharing.

### PR DESCRIPTION
**Pull request by yulisuliman**
- Creating a Vagrantfile that contains the instructions about how to create and bring up a virtual machine (VM) for working on our project. Our Vagrantfile would bring up a VM that is based on the fedora/34-cloud-base box.

- Making changes in the .gitignore file, making Git ignore the.vagrant directory.

fix #1

### CODE REVIEW

**Comment by natifridman** [comment]
@yulisuliman Please link this PR to the issue by adding the word fix before the issue number. This will link the issue and will close it automatically after it will be merged.
See also https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Review by MatanP12 — APPROVED** [review]
Approved

**Review by TomerNewmanPrograms — APPROVED** [review]
Looks ok

**Review by natifridman — APPROVED** [review]
@yulisuliman Please squash your commits so we can merge it

**Pull request merged**
