### PR TITLE
Add profile tests

### LINKED ISSUE #118: Editing Profile and users test
- Add more tests to users model view
- Giving more meaningful names to functions

### PR DESCRIPTION
**Pull request by MatanP12**
- Adding more test to users models views
- Giving meaningful names to existing test functions
- Moving the tests to a global tests folder.
- Moving all the fixtures to a main `conftest` file

fix #118

### CODE REVIEW

**Comment by TomerNewmanPrograms** [comment]
Not a complete fix but some sort of workaround - move the `conftest.py` file to the BASE_DIR (where `manage.py` is located) and then the tests work, what do you think?

**Comment by TomerNewmanPrograms** [comment]
Not a complete fix but some sort of workaround - move the `conftest.py` file to the BASE_DIR (where `manage.py` is located) and then the tests work, what do you think?

**Comment by natifridman** [comment]
> Not a complete fix but some sort of workaround - move the `conftest.py` file to the BASE_DIR (where `manage.py` is located) and then the tests work, what do you think?

As Tomer mentioned, since your `conftest` is under posts and the test is under users it won't be recognized (see more about conftest folders [here](https://docs.pytest.org/en/7.1.x/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files)).

You can put the `conftest` file in the main folder as Tomer suggested.

**Comment by MatanP12** [comment]
> > Not a complete fix but some sort of workaround - move the `conftest.py` file to the BASE_DIR (where `manage.py` is located) and then the tests work, what do you think?
> 
> As Tomer mentioned, since your `conftest` is under posts and the test is under users it won't be recognized (see more about conftest folders [here](https://docs.pytest.org/en/7.1.x/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files)).
> 
> You can put the `conftest` file in the main folder as Tomer suggested.

I moved the `conftest` file to the root directory, but it seems odd keep it there alone without a context.
Maybe should I move all the test files to one global folder in the `BASE_DIR` with the `conftest` file?

**Comment by TomerNewmanPrograms** [comment]
> > > Not a complete fix but some sort of workaround - move the `conftest.py` file to the BASE_DIR (where `manage.py` is located) and then the tests work, what do you think?
> 
> > 
> 
> > As Tomer mentioned, since your `conftest` is under posts and the test is under users it won't be recognized (see more about conftest folders [here](https://docs.pytest.org/en/7.1.x/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files)).
> 
> > 
> 
> > You can put the `conftest` file in the main folder as Tomer suggested.
> 
> 
> 
> I moved the `conftest` file to the root directory, but it seems odd keep it there alone without a context.
> 
> Maybe I should move all the test files to one global folder in the `BASE_DIR` with the `conftest` file?

Sounds great, and for each app you can make a new folder in the tests folder.

**Review by TomerNewmanPrograms — CHANGES_REQUESTED** [review]
I think for consistency we should call the folder `post_tests` instead of `post tests` (under tests folder), every thing else looks great!

**Comment by MatanP12** [comment]
> I think for consistency we should call the folder `post_tests` instead of `post tests` (under tests folder), every thing else looks great!

Done

**Review by TomerNewmanPrograms — APPROVED** [review]

**Review by yulisuliman — CHANGES_REQUESTED** [review]
I think the changes in direct_message/tests,py not is not part of this PR

**Comment by MatanP12** [comment]
> I think the changes in direct_message/tests,py not is not part of this PR. Beside that, very nice work !

I just changed the tests to be more readable 🙂

**Review by yulisuliman — APPROVED** [review]

**Comment by natifridman** [comment]
> * Adding more test to users models views
> * Giving meaningful names to existing test functions
> 
> fix #118

The PR description only contains tests for users, while you also move the `posts` and `direct_messages` tests

**Comment by natifridman** [comment]
I think you should change the `post_test` folder name to `posts_test` since the app name is `posts`

**Comment by MatanP12** [comment]
> I think you should change the `post_test` folder name to `posts_test` since the app name is `posts`

Done!

**Review by TomerNewmanPrograms — DISMISSED** [review]

**Comment by AlonShakaroff** [comment]
Nice work!
LGTM

**Review by AlonShakaroff — DISMISSED** [review]

**Review by yulisuliman — DISMISSED** [review]

**Comment by natifridman** [comment]
> > * Adding more test to users models views
> > * Giving meaningful names to existing test functions
> > 
> > fix #118
> 
> The PR description only contains tests for users, while you also move the `posts` and `direct_messages` tests

The PR description still does not includes all the changes here. Should the change in `posts` and `direct_messages` tests be part of this PR?

**Comment by MatanP12** [comment]
> > > * Adding more test to users models views
> > > * Giving meaningful names to existing test functions
> > > 
> > > fix #118
> > 
> > 
> > The PR description only contains tests for users, while you also move the `posts` and `direct_messages` tests
> 
> The PR description still does not includes all the changes here. Should the change in `posts` and `direct_messages` tests be part of this PR?

I would like to add it as part of the PR, the `conftest` issue added more things to consider.

**Comment by natifridman** [comment]
> I would like to add it as part of the PR, the `conftest` issue added more things to consider.

So please edit the PR description accordingly

**Comment by MatanP12** [comment]
> > I would like to add it as part of the PR, the `conftest` issue added more things to consider.
> 
> So please edit the PR description accordingly

Edited :)

**Review by natifridman — APPROVED** [review]

**Review by TomerNewmanPrograms — APPROVED** [review]

**Review by yulisuliman — APPROVED** [review]

**Review by natifridman — APPROVED** [review]

**Pull request merged**
