### PR TITLE
Updated the ERD

### LINKED ISSUE #29: Updating the ERD
- Changing the post, resume, and poll tables to fit the inheritance stracture.

### PR DESCRIPTION
**Pull request by AlonShakaroff**
- Updated the ResuMe ERD
- Added docs directory

fix #29

### CODE REVIEW

**Review by OmerCS8 — DISMISSED** [review]
LGTM

**Review by yulisuliman — DISMISSED** [review]
Look good!

**Review by MatanP12 — DISMISSED** [review]
LGTM

**Comment by natifridman** [comment]
- If `Profile` extends `User`, so everything should be connected to `Profile` and not to `User`
- Why do you need to save the number of ratings and voters? I think we already discussed it
- Message: **receiver**. If you go with `receiver`, you should also use `sender`
- Profile: no need for ID as you already have it in `User`

**Comment by AlonShakaroff** [comment]
> * If `Profile` extends `User`, so everything should be connected to `Profile` and not to `User`
> * Why do you need to save the number of ratings and voters? I think we already discussed it
> * Message: **receiver**. If you go with `receiver`, you should also use `sender`
> * Profile: no need for ID as you already have it in `User`

Ok thank you, I fixed everything, we will make the adjustments in our code.

**Comment by TomerNewmanPrograms** [comment]
> * If `Profile` extends `User`, so everything should be connected to `Profile` and not to `User`
For example in the message table, why should it connect to the Profile and not the User?
Message is between every two Users and not Profiles.
@natifridman

**Comment by AlonShakaroff** [comment]
> > * If `Profile` extends `User`, so everything should be connected to `Profile` and not to `User`
> >   For example in the message table, why should it connect to the Profile and not the User?
> >   Message is between every two Users and not Profiles.
> >   @natifridman

To make it more clear, In all of the cases we refer to the User/Profile we only use the data that is in Django's User model, and the data used in the Profile will only be used on the profile page.
Meaning every time we will want to access the User data we will have to access it through the profile and that seems to us a bit off. (for example : someProfile.user.username instead of direct access).
So we wanted to know what is our motive and necessity to refer to the Profile model?

**Review by MatanP12 — APPROVED** [review]
LGTM

**Review by TomerNewmanPrograms — APPROVED** [review]
lgtm

**Review by yulisuliman — APPROVED** [review]
Looks great!

**Review by natifridman — APPROVED** [review]
Please remember to update the ERD here if you change something later

**Pull request merged**
