### PR TITLE
Adding direct_message views

### LINKED ISSUE #137: Adding Messages view
- Adding Messages HTML
- Adding Messages view
- Adding Messages URLs

### PR DESCRIPTION
**Pull request by TomerNewmanPrograms**
- Adding direct_message_list view and direct_message_create view
- Adding main_messages, message_form and direct_message html files
- Adding direct button on base.html
- Adding direct_message_view tests
  fix #137

### CODE REVIEW

**Comment by TomerNewmanPrograms** [comment]
<h1>For now it looks like this:</h1>
image
image
image

**Review by AlonShakaroff — APPROVED** [review]
Nice work, LGTM! 👍

**Review by MatanP12 — DISMISSED** [review]
LGTM! nice work

**Comment by natifridman** [comment]
Maybe we can add some more tests here? For example, what should happen after a new message is created, a redirect or something else?

**Comment by TomerNewmanPrograms** [comment]
> Maybe we can add some more tests here? For example, what should happen after a new message is created, a redirect or something else?

Done

**Review by AlonShakaroff — DISMISSED** [review]
LGTM

**Review by yulisuliman — DISMISSED** [review]

**Review by natifridman — APPROVED** [review]

**Comment by yulisuliman** [comment]
@TomerNewmanPrograms Please squash all the commit :)

**Review by yulisuliman — APPROVED** [review]

**Review by MatanP12 — APPROVED** [review]

**Review by natifridman — APPROVED** [review]

**Pull request merged**
