### PR TITLE
Add profession to users model

### LINKED ISSUE #78: Change tests name to be more meaningful in users

### PR DESCRIPTION
**Pull request by yulisuliman**
- Adding profession field to users model.
- Creating test for profession field.
- Changing tests name to be more meaningful.

fix #78 #75

### CODE REVIEW

**Review by TomerNewmanPrograms — COMMENTED** [review]
@yulisuliman  @MatanP12  @OmerCS8  @AlonShakaroff 
If we later want to quarry and sort the professions, I think we need to hold some sort of `enum`  for professions (software engineer, account manager and product for example)

**Review by MatanP12 — COMMENTED** [review]
Did you check that the migrations test data work?

**Comment by MatanP12** [comment]
> @yulisuliman @MatanP12 @OmerCS8 @AlonShakaroff If we later want to quarry and sort the professions, I think we need to hold some sort of `enum` for professions (software engineer, account manager and product for example)

I think we discussed this, right now we don't want to use any premade enums or tags, the profession should be like the subtitle in linkedIn

**Comment by yulisuliman** [comment]
> @yulisuliman @MatanP12 @OmerCS8 @AlonShakaroff If we later want to quarry and sort the professions, I think we need to hold some sort of `enum` for professions (software engineer, account manager and product for example)

Yesterday at a zoom meeting we decided to do a free option for profession.

**Comment by yulisuliman** [comment]
> Did you check that the migrations test data work?

Yes :)

**Review by TomerNewmanPrograms — APPROVED** [review]

**Review by MatanP12 — APPROVED** [review]
LGTM

**Review by natifridman — APPROVED** [review]

**Pull request merged**
