### PR TITLE
Replacing 'resumeApp' name to 'posts'

### LINKED ISSUE #24: Change the ResumeApp name to posts
Change the ResumeApp name to posts,
also apply the name change in all the subdirectories and files and in all usages.

### PR DESCRIPTION
**Pull request by OmerCS8**
- Changing the 'resumeApp' app name to 'posts' in order to match Django's app naming convention.
- Adding some profile pics and resumes for default users
fix #24

### CODE REVIEW

**Review by TomerNewmanPrograms — DISMISSED** [review]
LGTM

**Review by AlonShakaroff — APPROVED** [review]
LGTM

**Review by natifridman — DISMISSED** [review]
Please squash your commits

**Comment by OmerCS8** [comment]
> Please squash your commits

done 👍

**Review by MatanP12 — APPROVED** [review]
LGTM

**Review by AlonShakaroff — APPROVED** [review]
LGTM

**Review by natifridman — APPROVED** [review]

**Pull request merged**
